---
# Vagrant adds '127.0.0.1 ipa.noggin.test ipa' as the first line in /etc/hosts
# and freeipa doesnt like that, so we remove it
- name: Tweak /etc/hosts
  lineinfile:
    path: /etc/hosts
    regexp: >
      127\.0\.0\.1 *.*\.test.*
    state: absent

- name: Install RPM packages
  dnf:
    name:
      - git
      - vim
      - freeipa-server
      - python-freeipa
      - python-faker
    state: present

- name: uninstall existing freeipa server
  shell: test -f /var/log/ipaserver-install.log && ipa-server-install --uninstall --unattended
  ignore_errors: yes
  changed_when: "False"

- name: install freeipa server
  shell: umask 022; ipa-server-install -a {{ ipa_admin_password }} --hostname=ipa.noggin.test -r {{ krb_realm }} -p {{ krb_master_password }} -n noggin.test -U

- name: get freeipa-fas
  git:
    repo: https://github.com/fedora-infra/freeipa-fas.git
    dest: /home/vagrant/freeipa-fas

- name: install freeipa-fas
  shell: ./install.sh
  args:
    chdir: /home/vagrant/freeipa-fas/

- name: create backup of clean FreeIPA server data
  shell: ipa-backup

# ipa-backup creates the backup with a datetime in the dirname. here
# we just copy it to noggin-clean so we can reference it easier in the
# bash alias.
- name: copy clean backup
  shell: mv /var/lib/ipa/backup/ipa-full* /var/lib/ipa/backup/backup-clean

- name: Install the .bashrc
  template:
      src: .bashrc
      dest: /home/vagrant/.bashrc
      mode: 0644
      owner: vagrant
      group: vagrant

- name: copy the create data script
  template:
      src: create_dummy_data.py
      dest: /home/vagrant/create_dummy_data.py
      mode: 0644
      owner: vagrant
      group: vagrant

- name: create dummy data
  shell: python create_dummy_data.py
  args:
    chdir: /home/vagrant/
