repos:
  # - repo: https://github.com/asottile/pyupgrade
  #   rev: v2.15.0
  #   hooks:
  #     - id: pyupgrade
  #       args:
  #         - --py39-plus

  - repo: https://github.com/psf/black
    rev: 24.10.0
    hooks:
      - id: black
        language_version: python3
        args: ["--check", "--diff"]

  - repo: https://github.com/pycqa/flake8
    rev: 7.1.1
    hooks:
      - id: flake8

  - repo: https://github.com/pycqa/isort
    rev: 5.13.2
    hooks:
      - id: isort
        args: ["-c", "--diff"]

  - repo: https://github.com/Lucas-C/pre-commit-hooks-bandit
    rev: v1.0.6
    hooks:
      - id: python-bandit-vulnerability-check
        alias: bandit
        args: ["-r", "noggin/", "-ll"]
  # - repo: local
  #   hooks:
  #     - id: bandit-local
  #       name: bandit
  #       entry: bandit
  #       args: ["-r", "noggin/", "-ll"]
  #       pass_filenames: false
  #       language: system

  - repo: https://github.com/myint/rstcheck
    rev: v6.2.4
    hooks:
      - id: rstcheck
        # Use ignore-messages here until we can put it in the release_notes directly
        # https://github.com/rstcheck/rstcheck/issues/167
        args: ["-r", "docs", "--ignore-messages=Duplicate implicit target name"]
        additional_dependencies: [sphinx]
